"""Add AuditLog table

Revision ID: 031415e4fa5c
Revises: 64d66e4ea85e
Create Date: 2026-09-17 16:38:36.066889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031415e4fa5c'
down_revision = '64d66e4ea85e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
