"""Add SLA timestamps to Appointment

Revision ID: 641a169e7666
Revises: 031415e4fa5c
Create Date: 2026-09-25 12:29:57.352547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641a169e7666'
down_revision = '031415e4fa5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'custom_role_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'custom_role_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('appointments', 'checked_out_at')
    op.drop_column('appointments', 'admitted_at')
    op.drop_column('appointments', 'checked_in_at')
    # ### end Alembic commands ###
