"""create v1 core tables

Revision ID: 706059c577fa
Revises: 5a085a2033e8
Create Date: 2026-08-27 12:04:41.061060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706059c577fa'
down_revision = '5a085a2033e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
